<?PHP
session_start();
?>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Book Store</title>
<link rel="stylesheet" type="text/css" href="style.css" />

</head>
<body>
<div id="wrap">

       <div class="header">
       		<embed src="images/bookstore.swf" height="90px">
        <div id="menu">
            <ul>                                                                       
            <li><a href="index.php">home</a></li>
            <li><a href="about.php">about us</a></li>
            <li class="selected"><a href="category.php">books</a></li>
            <li><a href="specials.php">specials books</a></li>
            <li><a href="choosePage.php">my accout</a></li>
            <li><a href="gift.php">gift</a></li>
            <li><a href="search.php">search</a></li>
            <li><a href="contact.php">contact</a></li>
            <li><a href="order.php">order</a></li>
            <li><a href="faq.php">faq</a></li>
            <li><a href="references.php">references</a></li>
            </ul>
        </div>     
            
            
       </div> 
       
       
       <div class="center_content">
       	<div class="left_content">
        	<!--<div class="crumb_nav">
            <a href="index.php">home</a> &gt;&gt; category name
            </div>-->
            <div class="title"><span class="title_icon"><img src="images/bullet1.gif" alt="" title="" /></span>Category books</div>
           
           <div class="new_products">
           
           <div class="crumb_nav">
            <label>Browse Books by Subjects:</label>
                          
                <!-- try redirect and change parameter of category.php based on selected category -->
                <select id="category" onchange="location.href='category.php?cat=' + this.options[this.selectedIndex].value" >
                    <option value="all" selected="selected">All</option>
                    <option value="computer">Computer</option>
                    <option value="fantasy">Fantasy</option>
                    <option value="romance">Romance</option>
                    <option value="horror">Horror</option>
                    <option value="science_fiction">Science Fiction</option>
                </select>
                      
            </div>
            
            <!-- the following part is to be generated by xml&xsl --->                  
 <!------------------------------------------------------------------>
            
             <?php
            // get the id of book
            $cat = "all";
            if (isset($_GET['cat']))
                $cat = $_GET['cat'];

            // Load the XML of all books
            $xml = new DOMDocument;
            $xml->load('xml/books.xml');

            // filter books by category
            $xpath = new DOMXPath($xml);
            if($cat == 'all'){
                $query = "//catalog/book";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=0</script>";
            }else if($cat == 'computer'){
                $query = "//catalog/book[@genre='Computer']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=1</script>";
            }else if($cat == 'fantasy'){
                $query = "//catalog/book[@genre='Fantasy']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=2</script>";
            }else if($cat == 'romance'){
                $query = "//catalog/book[@genre='Romance']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=3</script>";
            }else if($cat == 'horror'){
                $query = "//catalog/book[@genre='Horror']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=4</script>";
            }else if($cat == 'science_fiction'){
                $query = "//catalog/book[@genre='Science Fiction']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=5</script>";
            }
            $elements = $xpath->query($query);

            // make a new xml document and append catalog node as parent
            $newxml = new DOMDocument;
            $newxml->loadXML("<catalog></catalog>");
            foreach ($elements as $element) {
                $element = $newxml->importNode($element, true);
                $newxml->documentElement->appendChild($element);
            }


            // load xsl
            $xsl = new DOMDocument;
            $xsl->load('xml/book.xsl');

            // Configure the transformer
            $proc = new XSLTProcessor;
            $proc->importStyleSheet($xsl); // attach the xsl rules

            // output the transformed xsl
            echo str_replace("<?xml version=\"1.0\"?>", "" ,$proc->transformToXML($newxml)) ;

            ?>

 <!-- the above part is to be generated by xml&xsl --->                  
 <!------------------------------------------------------------------>
           <!-- <div class="pagination">
            <span class="disabled"><<</span><span class="current">1</span><a href="#?page=2">2</a><a href="#?page=3">3</a>…<a href="#?page=199">10</a><a href="#?page=200">11</a><a href="#?page=2">>></a>
            </div>  -->
            
            </div> 
          
            
        <div class="clear"></div>
        </div><!--end of left content-->
        
        <div class="right_content">
             
                <?php include 'include/side_bar.php';?>
             
        </div><!--end of right content-->
        
        
       
       
       <div class="clear"></div>
       </div><!--end of center content-->
       
              
       <div class="footer">
       	<div class="left_footer"><img src="images/footer_logo.gif" alt="" title="" /><br /> <a href="http://csscreme.com/freecsstemplates/" title="free templates"><img src="images/csscreme.gif" alt="free templates" title="free templates" border="0" /></a></div>
        <div class="right_footer">
        <a href="index.php">home</a>
        <a href="about.php">about us</a>
        <a href="search.php">search</a>
        <a href="license.txt">privacy policy</a>
        <a href="contact.php">contact us</a>
       
        </div>
        <div class="copyright">
          &copy; Deakin University, School of Information Technology. This web page has been developed as a student assignment for the unit SIT203: Web Programming. Therefore it is not part of the University's authorised web site. DO NOT USE THE INFORMATION CONTAINED ON THIS WEB PAGE IN ANY WAY
        </div>
        
       
       </div>
    

</div>

</body>
</html>