<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Book Store</title>
<link rel="stylesheet" type="text/css" href="../style.css" />

</head>
<body>
<div id="wrap">

       <div class="header">
       		<div class="logo"><a href="../index.php"><img src="images/logo.gif" alt="" title="" border="0" /></a></div>            
        <div id="menu">
            <ul>                                                                       
            <li class="selected"><a href="index.php">Home</a></li>
			<li><a href="users.php">Users</a></li>
            <li><a href="contacts.php">Contact Requests</a></li>
            <li><a href="orders.php">Orders</a></li>
            </ul>
        </div>     
            
            
       </div> 
       
       
       <div class="center_content" style="width:100%;">
       	<div class="left_content" style="width:100%;">
        	<!--<div class="crumb_nav">
            <a href="../index.php">home</a> &gt;&gt; category name
            </div>-->
            <div class="title"><span class="title_icon"><img src="images/bullet1.gif" alt="" title="" /></span>Admin Panel</div>
           
           <div class="new_products" style="width:100%;">
            
            <!-- the following part is to be generated by xml&xsl --->                  
 <!------------------------------------------------------------------>
            <br><br><br>
			<center>
          <h2>
		  Welcome To Admin Panel
		  </h2>
		  </center>
 <!-- the above part is to be generated by xml&xsl --->                  
 <!------------------------------------------------------------------>
           <!-- <div class="pagination">
            <span class="disabled"><<</span><span class="current">1</span><a href="../#?page=2">2</a><a href="../#?page=3">3</a>…<a href="../#?page=199">10</a><a href="../#?page=200">11</a><a href="../#?page=2">>></a>
            </div>  -->
            
            </div> 
          
            
        <div class="clear"></div>
        </div><!--end of left content-->
        
       <!--end of right content-->
        
        
       
       
       <div class="clear"></div>
       </div><!--end of center content-->
       
              
       <div class="footer">
       	<div class="left_footer"><img src="images/footer_logo.gif" alt="" title="" /><br /> <a href="../http://csscreme.com/freecsstemplates/" title="free templates"><img src="images/csscreme.gif" alt="free templates" title="free templates" border="0" /></a></div>
        <div class="right_footer">
        <a href="../index.php">home</a>
        <a href="../about.php">about us</a>
        <a href="../search.php">search</a>
        <a href="../license.txt">privacy policy</a>
        <a href="../contact.php">contact us</a>
       
        </div>
        <div class="copyright">
          &copy; Deakin University, School of Information Technology. This web page has been developed as a student assignment for the unit SIT203: Web Programming. Therefore it is not part of the University's authorised web site. DO NOT USE THE INFORMATION CONTAINED ON THIS WEB PAGE IN ANY WAY
        </div>
        
       
       </div>
    

</div>

</body>
</html>