<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Book Store</title>
<link rel="stylesheet" type="text/css" href="../style.css" />

</head>
<body>
<div id="wrap">

       <div class="header">
       		<div class="logo"><a href="../index.php"><img src="images/logo.gif" alt="" title="" border="0" /></a></div>            
        <div id="menu">
            <ul>                                                                       
           <li><a href="index.php">Home</a></li>
		   <li><a href="users.php">Users</a></li>
            <li><a href="contacts.php">Contact Requests</a></li>
            <li class="selected"><a href="orders.php">Orders</a></li>
            </ul>
        </div>     
            
            
       </div> 
       
       
       <div class="center_content" style="width:100%;">
       	<div class="left_content" style="width:100%;">
        	<!--<div class="crumb_nav">
            <a href="../index.php">home</a> &gt;&gt; category name
            </div>-->
            <div class="title"><span class="title_icon"><img src="images/bullet1.gif" alt="" title="" /></span>Order Tracking</div>
           
           <div class="new_products" style="width:100%;">
            
            <!-- the following part is to be generated by xml&xsl --->                  
 <!------------------------------------------------------------------>
            
             <?php
            // get the id of book
            $cat = "all";
            if (isset($_GET['cat']))
                $cat = $_GET['cat'];

            // Load the XML of all books
            $xml = new DOMDocument;
            $xml->load('../xml/orders.xml');

            // filter books by category
            $xpath = new DOMXPath($xml);
            if($cat == 'all'){
                $query = "//catalog/contact";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=0</script>";
            }else if($cat == 'computer'){
                $query = "//catalog/contact[@genre='Computer']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=1</script>";
            }else if($cat == 'fantasy'){
                $query = "//catalog/contact[@genre='Fantasy']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=2</script>";
            }else if($cat == 'romance'){
                $query = "//catalog/contact[@genre='Romance']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=3</script>";
            }else if($cat == 'horror'){
                $query = "//catalog/contact[@genre='Horror']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=4</script>";
            }else if($cat == 'science_fiction'){
                $query = "//catalog/contact[@genre='Science Fiction']";

                // change the selected drop down list of categoty by javascript
                echo "<script>document.getElementById('category').selectedIndex=5</script>";
            }
            $elements = $xpath->query($query);
			
            // make a new xml document and append catalog node as parent
            $newxml = new DOMDocument;
            $newxml->loadXML("<catalog></catalog>");
            foreach ($elements as $element) {
                $element = $newxml->importNode($element, true);
                $newxml->documentElement->appendChild($element);
            }


            // load xsl
            $xsl = new DOMDocument;
            $xsl->load('../xml/orders.xsl');

            // Configure the transformer
            $proc = new XSLTProcessor;
            $proc->importStyleSheet($xsl); // attach the xsl rules

            // output the transformed xsl
            echo str_replace("<?xml version=\"1.0\"?>", "" ,$proc->transformToXML($newxml)) ;

            ?>

 <!-- the above part is to be generated by xml&xsl --->                  
 <!------------------------------------------------------------------>
           <!-- <div class="pagination">
            <span class="disabled"><<</span><span class="current">1</span><a href="../#?page=2">2</a><a href="../#?page=3">3</a>…<a href="../#?page=199">10</a><a href="../#?page=200">11</a><a href="../#?page=2">>></a>
            </div>  -->
            
            </div> 
          
            
        <div class="clear"></div>
        </div><!--end of left content-->
        
       <!--end of right content-->
        
        
       
       
       <div class="clear"></div>
       </div><!--end of center content-->
       
              
       <div class="footer">
       	<div class="left_footer"><img src="images/footer_logo.gif" alt="" title="" /><br /> <a href="../http://csscreme.com/freecsstemplates/" title="free templates"><img src="images/csscreme.gif" alt="free templates" title="free templates" border="0" /></a></div>
        <div class="right_footer">
        <a href="../index.php">home</a>
        <a href="../about.php">about us</a>
        <a href="../search.php">search</a>
        <a href="../license.txt">privacy policy</a>
        <a href="../contact.php">contact us</a>
       
        </div>
        <div class="copyright">
          &copy; Deakin University, School of Information Technology. This web page has been developed as a student assignment for the unit SIT203: Web Programming. Therefore it is not part of the University's authorised web site. DO NOT USE THE INFORMATION CONTAINED ON THIS WEB PAGE IN ANY WAY
        </div>
        
       
       </div>
    

</div>

</body>
</html>